# Generated by Django 2.1.2 on 2018-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
                ('homepage', models.CharField(max_length=1000)),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
    ]
