# Generated by Django 2.1.2 on 2018-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dapp',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
