# Generated by Django 2.1.2 on 2018-10-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dapp_blockchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapp',
            name='current_fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dapp',
            name='fund_next_stage',
            field=models.IntegerField(default=10),
        ),
    ]
